# Generated by Django 3.1.6 on 2021-02-03 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisalmodule',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_appraisal', to='management.empoyeemodule', verbose_name='Approved By'),
        ),
        migrations.AlterField(
            model_name='appraisalmodule',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_appraisal', to='management.empoyeemodule', verbose_name='Employee Name'),
        ),
    ]
