# Generated by Django 3.1.6 on 2021-02-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20210203_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='empoyeemodule',
            name='manage_employee',
            field=models.ManyToManyField(blank=True, null=True, related_name='_empoyeemodule_manage_employee_+', to='management.EmpoyeeModule'),
        ),
    ]
