# Generated by Django 3.1.6 on 2021-02-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20210203_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmodule',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'InActive')], default=0),
        ),
    ]
